### ISSUE TITLE
[v0.1] 프로젝트 개발환경 구축 

### ISSUE THREAD

**Issue by JisooOh94** [JisooOh94/SpringTraining#1]
### 요구사항
* Spring 웹어플리케이션 프로젝트 개발을 위한 초기 환경을 구축한다.

### Features
- [x] MVC 패턴 기반 Spring 프로젝트 개발
- [x] log4j2 + slf4j 적용
- [x] Profile + Property 주입 적용
- [x] test code 작성 환경 구축
- [x] 임베디드 database 구축

**Comment by EddieYS95** [comment]
Fearure들 언제 적용되나요?
